// Dados compartilhados de produtos para todo o projeto

export interface Product {
  id: string;
  title: string;
  price: string;
  unit: string;
  image?: string;
  badge?: string;
  description?: string;
  category: string;
  marca?: string; // Marca/Fabricante/Industrializador do produto
}

export const products: Product[] = [
  // Hortifruti
  {
    id: "1",
    title: "Tomate Italiano",
    price: "5,99",
    unit: "kg",
    image: "/produtos/tomate_italiano.jpg",
    badge: "Oferta",
    category: "hortifruti",
    description: "Tomate italiano fresco e saboroso, ideal para saladas, molhos e preparações culinárias. Cultivado com cuidado para garantir qualidade e sabor excepcionais.",
  },
  {
    id: "2",
    title: "Banana Prata",
    price: "3,49",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Banana prata doce e nutritiva, rica em potássio e vitaminas. Perfeita para consumo in natura ou em receitas doces. Fruta fresca e de qualidade superior.",
  },
  {
    id: "5",
    title: "Alface Americana",
    price: "2,99",
    unit: "un",
    image: "",
    category: "hortifruti",
    description: "Alface americana crocante e fresca, perfeita para saladas e sanduíches.",
  },
  {
    id: "6",
    title: "Batata Doce",
    price: "4,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Batata doce nutritiva e saborosa, rica em fibras e vitaminas.",
  },
  {
    id: "7",
    title: "Cebola Roxa",
    price: "3,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Cebola roxa fresca, ideal para saladas e preparações culinárias.",
  },
  {
    id: "8",
    title: "Maçã Gala",
    price: "6,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Maçã gala doce e crocante, perfeita para lanches saudáveis.",
  },
  {
    id: "33",
    title: "Cenoura",
    price: "3,49",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Cenoura fresca e crocante, rica em vitamina A.",
  },
  {
    id: "34",
    title: "Brócolis",
    price: "5,99",
    unit: "un", // Venda por unidade, não por peso
    image: "",
    category: "hortifruti",
    description: "Brócolis fresco, rico em nutrientes e vitaminas.",
  },
  {
    id: "35",
    title: "Abacaxi",
    price: "4,99",
    unit: "un",
    image: "",
    category: "hortifruti",
    description: "Abacaxi doce e suculento, perfeito para sucos.",
  },
  {
    id: "36",
    title: "Mamão Papaya",
    price: "5,49",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Mamão papaya maduro e doce, rico em fibras.",
  },
  {
    id: "37",
    title: "Repolho",
    price: "2,99",
    unit: "un",
    image: "",
    category: "hortifruti",
    description: "Repolho fresco e crocante, ideal para saladas.",
  },
  {
    id: "38",
    title: "Pepino",
    price: "3,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Pepino fresco e crocante, perfeito para saladas.",
  },

  // Açougue (Churrasco) – cada item com imagem ÚNICA referente ao nome
  {
    id: "9",
    title: "Alcatra Peça",
    price: "39,90",
    unit: "kg",
    image: "",
    badge: "Oferta",
    category: "acougue",
    description: "Alcatra de primeira qualidade, macia e saborosa. Ideal para churrascos e refeições especiais.",
  },
  {
    id: "10",
    title: "Contrafilé",
    price: "45,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Contrafilé premium, suculento e macio. Perfeito para grelhados.",
  },
  {
    id: "11",
    title: "Peito de Frango",
    price: "18,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Peito de frango fresco e magro, rico em proteínas.",
  },
  {
    id: "20",
    title: "Picanha",
    price: "52,90",
    unit: "kg",
    image: "",
    badge: "Premium",
    category: "acougue",
    description: "Picanha premium, macia e suculenta. A melhor escolha para churrascos.",
  },
  {
    id: "21",
    title: "Costela de Porco",
    price: "22,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Costela de porco temperada, perfeita para assar.",
  },
  {
    id: "22",
    title: "Linguiça Toscana",
    price: "28,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Linguiça toscana artesanal, saborosa e temperada.",
  },
  {
    id: "23",
    title: "Coxa e Sobrecoxa de Frango",
    price: "15,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Coxa e sobrecoxa de frango frescas, ideais para grelhar.",
  },
  {
    id: "44",
    title: "Fraldinha",
    price: "38,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Fraldinha macia e saborosa, perfeita para churrasco.",
  },

  // Padaria
  {
    id: "12",
    title: "Pão Francês",
    price: "0,50",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Pão francês fresquinho, crocante por fora e macio por dentro.",
  },
  {
    id: "13",
    title: "Pão de Açúcar",
    price: "8,90",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Pão de açúcar artesanal, doce e macio.",
  },
  {
    id: "14",
    title: "Baguete",
    price: "3,50",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Baguete crocante e fresca, perfeita para acompanhar refeições.",
  },
  {
    id: "24",
    title: "Pão de Forma Integral",
    price: "6,90",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Pão de forma integral, rico em fibras e nutrientes.",
  },
  {
    id: "25",
    title: "Croissant",
    price: "4,50",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Croissant folhado e crocante, feito artesanalmente.",
  },
  {
    id: "26",
    title: "Bolo de Chocolate",
    price: "12,90",
    unit: "fatia",
    image: "",
    category: "padaria",
    description: "Bolo de chocolate caseiro, macio e delicioso.",
  },
  {
    id: "27",
    title: "Rosca Doce",
    price: "9,90",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Rosca doce tradicional, perfeita para o café da manhã.",
  },

  // Bebidas
  {
    id: "15",
    title: "Cerveja Skol 350ml",
    price: "2,99",
    unit: "un",
    image: "",
    badge: "Oferta",
    category: "bebidas",
    description: "Cerveja Skol gelada, refrescante e saborosa.",
  },
  {
    id: "16",
    title: "Refrigerante Coca-Cola 2L",
    price: "8,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Refrigerante Coca-Cola gelado, o sabor original.",
  },
  {
    id: "17",
    title: "Água Mineral 500ml",
    price: "1,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Água mineral natural, pura e refrescante.",
  },
  {
    id: "18",
    title: "Suco de Laranja Natural 1L",
    price: "6,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Suco de laranja natural, rico em vitamina C.",
  },
  {
    id: "28",
    title: "Cerveja Brahma 350ml",
    price: "2,79",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Cerveja Brahma gelada, refrescante e saborosa.",
  },
  {
    id: "29",
    title: "Refrigerante Guaraná Antarctica 2L",
    price: "7,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Refrigerante Guaraná Antarctica, o sabor brasileiro.",
  },
  {
    id: "30",
    title: "Água com Gás 500ml",
    price: "2,49",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Água com gás natural, refrescante e leve.",
  },
  {
    id: "31",
    title: "Suco de Uva Integral 1L",
    price: "8,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Suco de uva integral, natural e sem conservantes.",
  },
  {
    id: "32",
    title: "Energético Red Bull 250ml",
    price: "9,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Energético Red Bull, energia que te dá asas.",
  },

  // Outros
  {
    id: "3",
    title: "Arroz Branco 5kg",
    price: "24,90",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Arroz branco tipo 1, grãos selecionados e de alta qualidade. Base perfeita para suas refeições diárias. Embalagem de 5kg para maior economia.",
    // Nota: Marca será extraída automaticamente se estiver no título/descrição do Sysmo
    // Se não houver marca, o cliente deve verificar no Sysmo qual marca está cadastrada
  },
  {
    id: "4",
    title: "Azeite de Oliva",
    price: "32,90",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Azeite de oliva extra virgem, prensado a frio. Sabor intenso e aroma marcante, ideal para temperar saladas, massas e preparações gourmet.",
  },
  {
    id: "19",
    title: "Sabão em Pó OMO 1kg",
    price: "12,90",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Sabão em pó OMO com poder de limpeza superior.",
  },
  {
    id: "39",
    title: "Feijão Preto 1kg",
    price: "8,90",
    unit: "pct",
    image: "",
    badge: "Oferta",
    category: "ofertas",
    description: "Feijão preto tipo 1, selecionado e de qualidade.",
  },
  {
    id: "40",
    title: "Açúcar Cristal 1kg",
    price: "4,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Açúcar cristal refinado, doce e puro.",
  },
  {
    id: "41",
    title: "Óleo de Soja 900ml",
    price: "6,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Óleo de soja refinado, ideal para frituras.",
  },
  {
    id: "42",
    title: "Macarrão Espaguete 500g",
    price: "3,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Macarrão espaguete tipo 1, de qualidade superior.",
  },
  {
    id: "43",
    title: "Leite Integral 1L",
    price: "5,49",
    unit: "un",
    image: "",
    badge: "Oferta",
    category: "ofertas",
    description: "Leite integral fresco, rico em cálcio e proteínas.",
  },

  // ========== CORTES BOVINOS ADICIONAIS (cada um com imagem única) ==========
  {
    id: "100",
    title: "Filé Mignon",
    price: "68,90",
    unit: "kg",
    image: "",
    badge: "Premium",
    category: "acougue",
    description: "Filé mignon premium, o corte mais macio e nobre do boi.",
  },
  {
    id: "101",
    title: "Coxão Mole",
    price: "42,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Coxão mole macio e suculento, perfeito para bifes.",
  },
  {
    id: "102",
    title: "Coxão Duro",
    price: "35,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Coxão duro ideal para cozidos e assados.",
  },
  {
    id: "103",
    title: "Patinho",
    price: "36,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Patinho magro e saboroso, perfeito para bifes e carne moída.",
  },
  {
    id: "104",
    title: "Maminha",
    price: "48,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Maminha macia e suculenta, excelente para churrascos.",
  },
  {
    id: "105",
    title: "Acém",
    price: "32,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Acém versátil, ideal para refogados e assados.",
  },
  {
    id: "106",
    title: "Paleta",
    price: "28,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Paleta saborosa, perfeita para cozidos.",
  },
  {
    id: "107",
    title: "Músculo",
    price: "29,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Músculo ideal para ensopados e cozidos.",
  },
  {
    id: "108",
    title: "Costela Bovina",
    price: "34,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Costela bovina suculenta, perfeita para churrasco.",
  },
  {
    id: "109",
    title: "Carne Moída",
    price: "33,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Carne moída fresca, ideal para hambúrgueres e molhos.",
  },
  {
    id: "110",
    title: "Lagarto",
    price: "31,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Lagarto macio, perfeito para assados.",
  },
  {
    id: "111",
    title: "Cupim",
    price: "44,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Cupim suculento e saboroso, ideal para churrasco.",
  },

  // ========== CORTES SUÍNOS ==========
  {
    id: "112",
    title: "Lombo de Porco",
    price: "28,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Lombo de porco macio e saboroso, perfeito para assar.",
  },
  {
    id: "113",
    title: "Pernil de Porco",
    price: "24,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Pernil de porco suculento, ideal para assados.",
  },
  {
    id: "114",
    title: "Bisteca de Porco",
    price: "19,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Bisteca de porco temperada, perfeita para grelhar.",
  },
  {
    id: "115",
    title: "Paleta de Porco",
    price: "21,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Paleta de porco saborosa, ideal para cozidos.",
  },
  {
    id: "116",
    title: "Bacon",
    price: "32,90",
    unit: "kg",
    image: "",
    badge: "Oferta",
    category: "acougue",
    description: "Bacon defumado e crocante, perfeito para o café da manhã.",
  },

  // ========== CORTES OVINOS ==========
  {
    id: "117",
    title: "Pernil de Cordeiro",
    price: "58,90",
    unit: "kg",
    image: "",
    badge: "Premium",
    category: "acougue",
    description: "Pernil de cordeiro macio e suculento, nobre e saboroso.",
  },
  {
    id: "118",
    title: "Costela de Cordeiro",
    price: "52,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Costela de cordeiro temperada, perfeita para assar.",
  },
  {
    id: "119",
    title: "Paleta de Cordeiro",
    price: "48,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Paleta de cordeiro macia, ideal para assados.",
  },

  // ========== AVES ADICIONAIS ==========
  {
    id: "120",
    title: "Asa de Frango",
    price: "14,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Asa de frango fresca, perfeita para grelhar.",
  },
  {
    id: "121",
    title: "Frango Inteiro",
    price: "12,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Frango inteiro fresco, ideal para assar.",
  },
  {
    id: "122",
    title: "Coração de Frango",
    price: "16,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Coração de frango temperado, perfeito para churrasco.",
  },
  {
    id: "123",
    title: "Peito de Peru",
    price: "24,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Peito de peru magro e saboroso, rico em proteínas.",
  },

  // ========== PEIXES E FRUTOS DO MAR ==========
  {
    id: "124",
    title: "Salmão Filé",
    price: "68,90",
    unit: "kg",
    image: "",
    badge: "Premium",
    category: "acougue",
    description: "Salmão filé fresco, rico em ômega 3.",
  },
  {
    id: "125",
    title: "Tilápia Filé",
    price: "22,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Tilápia filé fresco, macio e saboroso.",
  },
  {
    id: "126",
    title: "Sardinha Fresca",
    price: "18,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Sardinha fresca, rica em proteínas e ômega 3.",
  },
  {
    id: "127",
    title: "Camarão Médio",
    price: "48,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Camarão médio fresco, perfeito para moquecas.",
  },
  {
    id: "128",
    title: "Polvo",
    price: "58,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Polvo fresco, macio e saboroso.",
  },

  // ========== EMBUTIDOS ==========
  {
    id: "129",
    title: "Linguiça Calabresa",
    price: "26,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Linguiça calabresa picante, perfeita para churrasco.",
  },
  {
    id: "130",
    title: "Linguiça Apimentada",
    price: "27,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Linguiça apimentada artesanal, saborosa e temperada.",
  },
  {
    id: "131",
    title: "Presunto Fatiado",
    price: "24,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Presunto fatiado defumado, perfeito para sanduíches.",
  },
  {
    id: "132",
    title: "Mortadela",
    price: "18,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Mortadela fatiada, saborosa e cremosa.",
  },
  {
    id: "133",
    title: "Salame",
    price: "42,90",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Salame italiano fatiado, nobre e saboroso.",
  },

  // ========== CHURRASCO – Acessórios e temperos ==========
  {
    id: "134",
    title: "Sal Grosso",
    price: "4,99",
    unit: "kg",
    image: "",
    category: "acougue",
    description: "Sal grosso para churrasco. Realça o sabor das carnes na grelha.",
  },
  {
    id: "135",
    title: "Tempero para Churrasco",
    price: "8,90",
    unit: "un",
    image: "",
    category: "acougue",
    description: "Tempero completo para churrasco. Carne, frango e costela.",
  },
  {
    id: "136",
    title: "Carvão para Churrasco",
    price: "18,90",
    unit: "pct",
    image: "",
    category: "acougue",
    description: "Carvão de qualidade para churrasco. Queima uniforme e duradoura.",
  },
  {
    id: "137",
    title: "Espetos para Churrasco",
    price: "24,90",
    unit: "un",
    image: "",
    category: "acougue",
    description: "Kit de espetos em aço inox. Ideal para carnes e legumes na churrasqueira.",
  },

  // ========== HORTIFRUTI ADICIONAIS ==========
  {
    id: "200",
    title: "Laranja Lima",
    price: "4,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Laranja lima doce e suculenta, rica em vitamina C.",
  },
  {
    id: "201",
    title: "Uva Itália",
    price: "12,90",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Uva Itália doce e crocante, perfeita para consumo.",
  },
  {
    id: "202",
    title: "Morango",
    price: "15,90",
    unit: "bandeja",
    image: "",
    badge: "Oferta",
    category: "hortifruti",
    description: "Morango fresco e doce, ideal para sobremesas.",
  },
  {
    id: "203",
    title: "Melancia",
    price: "3,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Melancia doce e refrescante, perfeita para o verão.",
  },
  {
    id: "204",
    title: "Melão",
    price: "4,49",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Melão doce e suculento, rico em água.",
  },
  {
    id: "205",
    title: "Manga",
    price: "5,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Manga madura e doce, perfeita para sucos.",
  },
  {
    id: "206",
    title: "Limão Taiti",
    price: "3,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Limão taiti azedo e suculento, ideal para temperos.",
  },
  {
    id: "207",
    title: "Kiwi",
    price: "18,90",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Kiwi doce e nutritivo, rico em vitamina C.",
  },
  {
    id: "208",
    title: "Pera",
    price: "8,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Pera doce e suculenta, perfeita para lanches.",
  },
  {
    id: "209",
    title: "Pêssego",
    price: "12,90",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Pêssego doce e macio, ideal para consumo.",
  },
  {
    id: "210",
    title: "Batata Inglesa",
    price: "4,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Batata inglesa fresca, versátil para diversas receitas.",
  },
  {
    id: "211",
    title: "Batata Baroa",
    price: "6,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Batata baroa doce e nutritiva.",
  },
  {
    id: "212",
    title: "Cebola Branca",
    price: "3,49",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Cebola branca fresca, ideal para temperos.",
  },
  {
    id: "213",
    title: "Alho",
    price: "18,90",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Alho fresco e aromático, essencial na cozinha.",
  },
  {
    id: "214",
    title: "Pimentão Vermelho",
    price: "8,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Pimentão vermelho doce e crocante.",
  },
  {
    id: "215",
    title: "Pimentão Amarelo",
    price: "9,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Pimentão amarelo doce e colorido.",
  },
  {
    id: "216",
    title: "Pimentão Verde",
    price: "7,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Pimentão verde fresco e crocante.",
  },
  {
    id: "217",
    title: "Abobrinha",
    price: "5,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Abobrinha fresca, ideal para refogados.",
  },
  {
    id: "218",
    title: "Berinjela",
    price: "6,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Berinjela fresca, perfeita para assados.",
  },
  {
    id: "219",
    title: "Chuchu",
    price: "3,99",
    unit: "kg",
    image: "",
    category: "hortifruti",
    description: "Chuchu fresco e leve, ideal para cozidos.",
  },
  {
    id: "220",
    title: "Couve-Flor",
    price: "6,99",
    unit: "un",
    image: "",
    category: "hortifruti",
    description: "Couve-flor fresca, rica em nutrientes.",
  },
  {
    id: "221",
    title: "Couve Manteiga",
    price: "3,99",
    unit: "maço",
    image: "",
    category: "hortifruti",
    description: "Couve manteiga fresca, perfeita para refogados.",
  },
  {
    id: "222",
    title: "Espinafre",
    price: "4,99",
    unit: "maço",
    image: "",
    category: "hortifruti",
    description: "Espinafre fresco, rico em ferro.",
  },
  {
    id: "223",
    title: "Rúcula",
    price: "5,99",
    unit: "maço",
    image: "",
    category: "hortifruti",
    description: "Rúcula fresca e picante, perfeita para saladas.",
  },
  {
    id: "224",
    title: "Agrião",
    price: "4,49",
    unit: "maço",
    image: "",
    category: "hortifruti",
    description: "Agrião fresco e picante, ideal para saladas.",
  },
  {
    id: "225",
    title: "Salsinha",
    price: "2,99",
    unit: "maço",
    image: "",
    category: "hortifruti",
    description: "Salsinha fresca, perfeita para temperos.",
  },
  {
    id: "226",
    title: "Cebolinha",
    price: "2,99",
    unit: "maço",
    image: "",
    category: "hortifruti",
    description: "Cebolinha fresca, ideal para temperos.",
  },
  {
    id: "227",
    title: "Coentro",
    price: "2,99",
    unit: "maço",
    image: "",
    category: "hortifruti",
    description: "Coentro fresco e aromático, perfeito para temperos.",
  },
  {
    id: "228",
    title: "Manjericão",
    price: "3,99",
    unit: "maço",
    image: "",
    category: "hortifruti",
    description: "Manjericão fresco e aromático, ideal para molhos.",
  },

  // ========== CEREAIS E GRÃOS ==========
  {
    id: "300",
    title: "Arroz Parboilizado 5kg",
    price: "26,90",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Arroz parboilizado tipo 1, grãos selecionados.",
  },
  {
    id: "301",
    title: "Arroz Integral 1kg",
    price: "8,90",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Arroz integral rico em fibras e nutrientes.",
  },
  {
    id: "302",
    title: "Feijão Carioca 1kg",
    price: "9,90",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Feijão carioca tipo 1, selecionado e de qualidade.",
  },
  {
    id: "303",
    title: "Lentilha 500g",
    price: "6,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Lentilha rica em proteínas e fibras.",
  },
  {
    id: "304",
    title: "Grão-de-Bico 500g",
    price: "7,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Grão-de-bico nutritivo, ideal para saladas.",
  },
  {
    id: "305",
    title: "Ervilha Seca 500g",
    price: "5,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Ervilha seca rica em proteínas.",
  },
  {
    id: "306",
    title: "Soja 1kg",
    price: "12,90",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Soja rica em proteínas vegetais.",
  },
  {
    id: "307",
    title: "Quinoa 500g",
    price: "18,90",
    unit: "pct",
    image: "",
    badge: "Premium",
    category: "ofertas",
    description: "Quinoa super alimento, rica em proteínas.",
  },
  {
    id: "308",
    title: "Aveia em Flocos 500g",
    price: "4,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Aveia em flocos rica em fibras.",
  },
  {
    id: "309",
    title: "Linhaça Dourada 200g",
    price: "8,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Linhaça dourada rica em ômega 3.",
  },
  {
    id: "310",
    title: "Chia 200g",
    price: "12,90",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Chia super alimento, rica em fibras e ômega 3.",
  },

  // ========== LATICÍNIOS ==========
  {
    id: "400",
    title: "Leite Desnatado 1L",
    price: "5,29",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Leite desnatado fresco, rico em cálcio.",
  },
  {
    id: "401",
    title: "Leite Semidesnatado 1L",
    price: "5,39",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Leite semidesnatado fresco, equilibrado.",
  },
  {
    id: "402",
    title: "Queijo Mussarela 500g",
    price: "18,90",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Queijo mussarela fatiado, cremoso e saboroso.",
  },
  {
    id: "403",
    title: "Queijo Prato 500g",
    price: "19,90",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Queijo prato fatiado, macio e saboroso.",
  },
  {
    id: "404",
    title: "Queijo Parmesão 200g",
    price: "24,90",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Queijo parmesão ralado, saboroso e aromático.",
  },
  {
    id: "405",
    title: "Requeijão Cremoso 250g",
    price: "6,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Requeijão cremoso, perfeito para pães.",
  },
  {
    id: "406",
    title: "Manteiga com Sal 200g",
    price: "8,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Manteiga com sal, cremosa e saborosa.",
  },
  {
    id: "407",
    title: "Margarina 500g",
    price: "5,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Margarina cremosa, ideal para uso diário.",
  },
  {
    id: "408",
    title: "Iogurte Natural 500g",
    price: "4,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Iogurte natural cremoso, rico em probióticos.",
  },
  {
    id: "409",
    title: "Iogurte de Morango 170g",
    price: "2,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Iogurte de morango doce e cremoso.",
  },
  {
    id: "410",
    title: "Cream Cheese 200g",
    price: "9,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Cream cheese cremoso, perfeito para bagels.",
  },
  {
    id: "411",
    title: "Ovos Brancos 12un",
    price: "8,99",
    unit: "dz",
    image: "",
    category: "ofertas",
    description: "Ovos brancos frescos, ricos em proteínas.",
  },
  {
    id: "412",
    title: "Ovos Caipira 12un",
    price: "12,90",
    unit: "dz",
    image: "",
    badge: "Premium",
    category: "ofertas",
    description: "Ovos caipira frescos, de galinhas criadas soltas.",
  },

  // ========== PADARIA ADICIONAL ==========
  {
    id: "500",
    title: "Pão de Hambúrguer",
    price: "6,90",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Pão de hambúrguer macio e saboroso.",
  },
  {
    id: "501",
    title: "Pão de Hot Dog",
    price: "5,90",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Pão de hot dog macio e fresquinho.",
  },
  {
    id: "502",
    title: "Pão Doce",
    price: "7,90",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Pão doce tradicional, macio e saboroso.",
  },
  {
    id: "503",
    title: "Sonho",
    price: "3,50",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Sonho recheado com creme, doce e macio.",
  },
  {
    id: "504",
    title: "Brigadeiro",
    price: "2,50",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Brigadeiro caseiro, doce e cremoso.",
  },
  {
    id: "505",
    title: "Torta de Frango",
    price: "18,90",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Torta de frango caseira, saborosa e recheada.",
  },
  {
    id: "506",
    title: "Torta de Palmito",
    price: "19,90",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Torta de palmito caseira, saborosa e cremosa.",
  },
  {
    id: "507",
    title: "Pão de Alho",
    price: "8,90",
    unit: "un",
    image: "",
    category: "padaria",
    description: "Pão de alho artesanal, crocante e saboroso.",
  },
  {
    id: "508",
    title: "Biscoito de Polvilho",
    price: "4,99",
    unit: "pct",
    image: "",
    category: "padaria",
    description: "Biscoito de polvilho crocante e leve.",
  },
  {
    id: "509",
    title: "Biscoito Recheado",
    price: "3,99",
    unit: "pct",
    image: "",
    category: "padaria",
    description: "Biscoito recheado doce e saboroso.",
  },

  // ========== BEBIDAS ADICIONAIS ==========
  {
    id: "600",
    title: "Cerveja Heineken 350ml",
    price: "4,99",
    unit: "un",
    image: "",
    badge: "Premium",
    category: "bebidas",
    description: "Cerveja Heineken gelada, premium e refrescante.",
  },
  {
    id: "601",
    title: "Cerveja Stella Artois 350ml",
    price: "5,49",
    unit: "un",
    image: "",
    badge: "Premium",
    category: "bebidas",
    description: "Cerveja Stella Artois gelada, premium belga.",
  },
  {
    id: "602",
    title: "Refrigerante Pepsi 2L",
    price: "7,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Refrigerante Pepsi gelado, refrescante.",
  },
  {
    id: "603",
    title: "Refrigerante Fanta Laranja 2L",
    price: "7,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Refrigerante Fanta Laranja gelado.",
  },
  {
    id: "604",
    title: "Suco de Maracujá 1L",
    price: "6,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Suco de maracujá natural, refrescante.",
  },
  {
    id: "605",
    title: "Suco de Acerola 1L",
    price: "7,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Suco de acerola rico em vitamina C.",
  },
  {
    id: "606",
    title: "Água de Coco 500ml",
    price: "3,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Água de coco natural, refrescante e hidratante.",
  },
  {
    id: "607",
    title: "Chá Mate 1L",
    price: "4,99",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Chá mate gelado, refrescante e saboroso.",
  },
  {
    id: "608",
    title: "Vinho Tinto 750ml",
    price: "24,90",
    unit: "un",
    image: "",
    badge: "Premium",
    category: "bebidas",
    description: "Vinho tinto seco, saboroso e encorpado.",
  },
  {
    id: "609",
    title: "Vinho Branco 750ml",
    price: "22,90",
    unit: "un",
    image: "",
    category: "bebidas",
    description: "Vinho branco suave, refrescante.",
  },
  {
    id: "610",
    title: "Café em Pó 500g",
    price: "12,90",
    unit: "pct",
    image: "",
    category: "bebidas",
    description: "Café em pó torrado, aromático e saboroso.",
  },
  {
    id: "611",
    title: "Café Solúvel 200g",
    price: "18,90",
    unit: "pct",
    image: "",
    category: "bebidas",
    description: "Café solúvel prático e saboroso.",
  },
  {
    id: "612",
    title: "Achocolatado em Pó 400g",
    price: "8,99",
    unit: "pct",
    image: "",
    category: "bebidas",
    description: "Achocolatado em pó cremoso e doce.",
  },

  // ========== MERCEARIA ==========
  {
    id: "700",
    title: "Macarrão Penne 500g",
    price: "4,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Macarrão penne tipo 1, de qualidade.",
  },
  {
    id: "701",
    title: "Macarrão Parafuso 500g",
    price: "4,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Macarrão parafuso tipo 1, versátil.",
  },
  {
    id: "702",
    title: "Molho de Tomate 340g",
    price: "3,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Molho de tomate pronto, saboroso.",
  },
  {
    id: "703",
    title: "Extrato de Tomate 350g",
    price: "4,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Extrato de tomate concentrado, versátil.",
  },
  {
    id: "704",
    title: "Farinha de Trigo 1kg",
    price: "5,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Farinha de trigo tipo 1, para bolos e pães.",
  },
  {
    id: "705",
    title: "Farinha de Mandioca 1kg",
    price: "6,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Farinha de mandioca tradicional, saborosa.",
  },
  {
    id: "706",
    title: "Açúcar Refinado 1kg",
    price: "5,49",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Açúcar refinado branco, doce e puro.",
  },
  {
    id: "707",
    title: "Sal Refinado 1kg",
    price: "2,99",
    unit: "pct",
    image: "",
    category: "ofertas",
    description: "Sal refinado iodado, essencial na cozinha.",
  },
  {
    id: "708",
    title: "Vinagre de Álcool 750ml",
    price: "3,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Vinagre de álcool, versátil para temperos.",
  },
  {
    id: "709",
    title: "Vinagre de Maçã 500ml",
    price: "6,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Vinagre de maçã natural, benéfico à saúde.",
  },
  {
    id: "710",
    title: "Milho Verde em Lata 200g",
    price: "3,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Milho verde em lata, prático e saboroso.",
  },
  {
    id: "711",
    title: "Ervilha em Lata 200g",
    price: "3,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Ervilha em lata, prática e nutritiva.",
  },
  {
    id: "712",
    title: "Atum em Lata 170g",
    price: "6,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Atum em lata, rico em proteínas e ômega 3.",
  },
  {
    id: "713",
    title: "Sardinha em Lata 125g",
    price: "4,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Sardinha em lata, rica em proteínas.",
  },
  {
    id: "714",
    title: "Palmito em Conserva 300g",
    price: "12,90",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Palmito em conserva, macio e saboroso.",
  },
  {
    id: "715",
    title: "Azeitonas Verdes 200g",
    price: "8,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Azeitonas verdes em conserva, saborosas.",
  },
  {
    id: "716",
    title: "Azeitonas Pretas 200g",
    price: "9,99",
    unit: "un",
    image: "",
    category: "ofertas",
    description: "Azeitonas pretas em conserva, saborosas.",
  },
];

// Lista de marcas conhecidas para extração
const MARCAS_CONHECIDAS = [
  "TIO JOAO", "TIO JOÃO", "CAMIL", "PRATO FINO", "KITANDA", "BROTO LEGAL",
  "TREMBOM", "DONA BENTA", "BOM ARROZ", "ARROZ DO CAMPO",
  "TIO URBANO", "TIO PEDRO", "TIO JORGE", "TIO PAULO", "TIO CARLOS",
  "JASMINE", "NATURALLIFE", "RAMPINELLI", "BLUE VILLE", "KARUI", "MANINHO",
  "NEILAR", "FIT FOOD", "DIA MAES", "DIA DOS PAIS", "OMO"
];

// Função para extrair marca do título/descrição
function extrairMarcaDoProduto(product: Product): string | undefined {
  // Se já tem marca, retornar
  if (product.marca) return product.marca;
  
  // Tentar extrair do título
  const texto = `${product.title} ${product.description || ''}`.toUpperCase();
  
  for (const marca of MARCAS_CONHECIDAS) {
    const marcaUpper = marca.toUpperCase();
    const regex = new RegExp(`\\b${marcaUpper.replace(/\s+/g, '\\s+')}\\b`, 'i');
    if (regex.test(texto)) {
      return marca;
    }
  }
  
  return undefined;
}

// Função auxiliar para enriquecer produto com marca extraída
function enriquecerProdutoComMarca(product: Product): Product {
  const marcaExtraida = extrairMarcaDoProduto(product);
  return {
    ...product,
    marca: marcaExtraida || product.marca,
  };
}

export const getProductById = (id: string): Product | undefined => {
  const product = products.find((p) => p.id === id);
  return product ? enriquecerProdutoComMarca(product) : undefined;
};

export const getProductsByCategory = (category: string): Product[] => {
  return products
    .filter((p) => p.category === category)
    .map(enriquecerProdutoComMarca);
};

export const searchProducts = (query: string): Product[] => {
  const lowerQuery = query.toLowerCase();
  return products
    .filter(
      (p) =>
        p.title.toLowerCase().includes(lowerQuery) ||
        p.description?.toLowerCase().includes(lowerQuery)
    )
    .map(enriquecerProdutoComMarca);
};

